apiVersion: v1
kind: Service
metadata:
  name: bigproject-app-nodeport
spec:
  selector:
    app: bigproject-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32665
  type: NodePort
  externalTrafficPolicy: Local
